"""add relationships

Revision ID: 2833dd796e98
Revises: a428f3c74b3e
Create Date: 2025-05-26 13:38:02.424223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2833dd796e98'
down_revision: Union[str, None] = 'a428f3c74b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_book_uid'), 'book', ['uid'], unique=False)
    op.create_foreign_key(None, 'book', 'user', ['user_uid'], ['uid'])
    op.create_index(op.f('ix_user_uid'), 'user', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_uid'), table_name='user')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_index(op.f('ix_book_uid'), table_name='book')
    op.drop_column('book', 'user_uid')
    # ### end Alembic commands ###
